<?php

/**
 * Implements hook_theme_registry_alter()
 * Dynamically register each of the available StoryServer themes.
 * @param $theme_registry
 */
function storyserver_theme_registry_alter(&$theme_registry) {
  $module_path = drupal_get_path('module', 'storyserver');
  $directories = glob($module_path . '/themes/*', GLOB_ONLYDIR);
  foreach ($directories as $directory) {
    $template = $directory . '/story';
    $theme    = 'storyserver_theme_' . basename($directory);

    $theme_info = array(
      'template'   => $template,
      'variables' => array(
        'story_id' => NULL,
        'story_theme' => NULL,
        'story' => NULL,
        'safeJson' => NULL,
        'appServer' => NULL,
      ),
      'type' => 'module',
      'theme path' => $module_path,
    );

    $theme_registry[$theme] = $theme_info;

  }
}

/**
 * Restrict the number of storyserver_story field instances per node to 1
 * @param $form
 * @param $form_state
 * @param $form_id
 */
function storyserver_form_field_storage_config_edit_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $entity = $form_state->getFormObject()->getEntity();
  $type = $entity->getType();
  if ($type == 'storyserver_story') {
    $form['cardinality_container']['cardinality']['#options'] = array(1);
    $form['cardinality_container']['cardinality']['#default_value'] = 1;
    $form['cardinality_container']['cardinality']['#disabled'] = TRUE;
  }
}